# Generated by Django 3.2.3 on 2021-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='toQuiz',
        ),
        migrations.AddField(
            model_name='questions',
            name='toQuiz',
            field=models.ManyToManyField(to='Quiz.Quiz'),
        ),
    ]
