# Generated by Django 3.2.3 on 2021-05-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210522_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField()),
                ('Quizname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.quiz')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.appuser')),
            ],
        ),
    ]
